// src/App.vue
<template>
  <div id="app" class="wrapper">
    <Navigation />
    <div class="divider"></div>
    <router-view />
  </div>
</template>

<script>
import Navigation from './components/Navigation.vue'

export default {
  name: 'App',
  components: {
    Navigation,
  }
}
</script>

<style lang="sass">
@import '../node_modules/bulma/bulma.sass'
</style>

// react/src/App.js
import Navigation from './Navigation.js'
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import Home from './Home';
import Help from './Help';
import './App.css';

function App() {
  return (
    <div id="app" className="wrapper">
      <Router>
        <Navigation />
        <Routes>
          <Route exact path="/" component={Home} />
          <Route path="/help" component={Help} />
        </Routes>
      </Router>
      <div className="divider"></div>
      <router-view />
    </div>
  );
}

export default App;
