// src/components/Sidebar/File.vue

<template>
  <p class="file">
    {{this.getPadding}}{{this.filename}}
  </p>
</template>

<script>


export default {
  name: 'File',
  props: {
      filename: String,
      padding: {
        default: "",
        type: String
      },
  },
  computed: {
      getPadding() {
          return this.padding + '\t';
      }
  },
}

</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.file{
  padding-left: 10%;
  background-color: #272727;
}
</style>

// react/src/File.js
import React, { Component } from 'react';
import './File.css';

class File extends Component {
    render() {
        const { filename, padding } = this.props;
        return(
            <p className="file">
                {padding + '\t'}{filename}
            </p>
        );
    }
}

export default File;
