// react/src/Home.js
import React, { Component } from 'react';
import VizWindow from './Visualization'
import Terminal from './Terminal'
// import Sidebar from './Sidebar'
import Navigation from './Navigation';
import Button from '@mui/material/Button';
import { FaRegEye, FaRegEyeSlash } from 'react-icons/fa';
import './Home.css';

class Home extends Component {
    closeVisualization() {
        document.getElementById("visualizations").style.display = "none";
        document.getElementById("opening-icon").style.display = "block";
        document.getElementById("terminal-wrapper").style.width = "100%";
    };
    
    openVisualization() {
        document.getElementById("visualizations").style.display = "block";
        document.getElementById("terminal-wrapper").style.width = "50%";
        document.getElementById("opening-icon").style.display = "none";
    }
    render() {
        return (
            <>
            <Navigation />
            <div className="columns">
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
                <div className="sidebar">
                    Sidebar
                    {/* <Sidebar /> */}
                </div>
            <div className="top-wrapper column">
                <div id="terminal-wrapper" className="terminal-wrapper">
                    <div className="headline-component">
                        <div className="terminal-header-title">Terminal</div>
                        <div className="visButtons">
                            <Button 
                                variant="contained" 
                                id="opening-icon"
                                className="button" 
                                color="secondary"
                                onClick={ this.openVisualization }
                            >
                                <FaRegEye />
                            </Button>
                        </div>
                    </div>
                    <Terminal />
                </div>
                <div id="visualizations" className="visualizations-wrapper">
                    <div className="headline-component">
                        <div className="visualization-header-title">Visualizations</div>
                        <div className="visButtons">
                            <Button 
                                variant="contained" 
                                id="closing-icon"
                                className="button" 
                                color="secondary"
                                onClick={ this.closeVisualization }
                            >
                                <FaRegEyeSlash />
                            </Button>
                        </div>
                    </div>
                    <VizWindow /> 
                </div>
            </div>   
        </div>
        </>
        );
    }
}

export default Home;

// vue/src/Home.vue
<template>
<div class="main">
  <Navigation />
  <div class="columns">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <div class="column is-fullheight is-one-fifth sidebar">
          <Sidebar />
      </div>
      <div class="top-wrapper column">
          <div id="terminal-wrapper" class="terminal-wrapper">
            <div class="headline-component">
              <div style="margin-left:auto;">
                Terminal
              </div>
              <div class="visButtons">
                <button 
                  id="opening-icon" 
                  class="button"
                  @click="openVisualization()"
                  title="Show visualization window"
                >
                  <font-awesome-icon icon="eye"/>
                </button>
              </div>
            </div>
              <Terminal />
          </div>
          <div id="visualizations" class="visualizations-wrapper">
            <div class="headline-component">
              <div style="margin-left:35%;">
                Visualizations 
              </div>
              <div class="visButtons">
                <button 
                    id="closing-icon" 
                    class="button"
                    @click="closeVisualization()"
                    title="Hide visualization window"
                  >
                    <font-awesome-icon icon="eye-slash"/>
                  </button>
              </div>
            </div>
            <VizWindow /> 
          </div>
      </div>   
  </div>
  </div>
</template>

<script>
import VizWindow from './VizWindow.vue'
import Terminal from '../../src/components./../vue/src/Terminal.vue'
import Sidebar from '../../src/components./../vue/src/Sidebar.vue'
import Navigation from './Navigation.vue'

import Vue from 'vue'
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.min.css'
import 'vue-material/dist/theme/default.css'
Vue.use(VueMaterial)

export default {
  name: 'Home',
  components: {
    VizWindow,
    Terminal,
    Sidebar,
    Navigation,
  },
  methods: {
    closeVisualization() {
      document.getElementById("visualizations").style.display = "none";
      document.getElementById("opening-icon").style.display = "block";
      document.getElementById("terminal-wrapper").style.width = "100%";
    },
    openVisualization() {
      document.getElementById("visualizations").style.display = "block";
      document.getElementById("terminal-wrapper").style.width = "50%";
      document.getElementById("opening-icon").style.display = "none";
    }
  }
}

</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
@import url("https://fonts.googleapis.com/css?family=Material+Icons");
.columns {
    height: 100vh;
}
.sidebar {
  padding-right: 0;
}
.column {
  width: 83%;
}
.general-wrapper {
  display:flex;
}
.top-wrapper {
  display:flex;
  padding-left: 0;
  max-width: 80%;
}
.headline-component {
  background-color: #53336B;
  border-color: green;
  color: white;
  border-width: 1px;
  border-style: solid;
  font-weight:bold;
  font-size: 20px;
  padding: 15px 0px;
  display: flex;
  flex-direction: row;
  justify-content: center;
  min-height: 72px;
}
#terminal-wrapper {
  width: 50%;
  background-color: black;
  position: relative;
  border-color: green;
}
.visualizations-wrapper {
  width: 50%;
  position: relative;
}
.closing-icon {
  background-color: #ce93d8;
  border-radius: 15px;
  position: absolute;
  right: 0;
  top: 5px;
}
#opening-icon {
  display:none;
}

.visButtons {
  margin-right: 12px;
  margin-left: auto;
}


@media only screen and (max-width: 770px) {
  .sidebar {
    display: none;
  }
  .terminal-wrapper {
    margin-left: 12px;
  }
  .top-wrapper {
    height: 100%;
  }
  #opening-icon, #closing-icon {
    width: 15%;
    margin: 0;
  }
  .top-wrapper {
    min-width: 100%;
  }
}
</style>
